group: travis_latest
language: python
cache: pip
python:
    - 2.7
    - 3.6
    #- nightly
    #- pypy
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
install:
    - pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks latergaignaignagaianh
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - ls
    - wget "https://drive.google.com/uc?export=download&confirm=D2ug&id=1UoE-XuW1SDLUjZmJPkIZ1MLxvQFgmTFH"
    - ls
    - python run_basics.py  # Can run only with python and tensorflow
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
